// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260715213232_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.CriteriaPreset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Category");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("IsActive");

                    b.ToTable("CriteriaPresets", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.GeneratedReport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AiProvider")
                        .HasColumnType("int")
                        .HasColumnName("AiProvider");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GeneratedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("QualityScore")
                        .HasColumnType("int")
                        .HasColumnName("QualityScore");

                    b.Property<Guid>("ReportRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReportRequestId");

                    b.HasIndex("UserId");

                    b.ToTable("GeneratedReports", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ReportExport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ContentType");

                    b.Property<DateTime>("ExportedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FileName");

                    b.Property<int>("Format")
                        .HasColumnType("int");

                    b.Property<Guid>("GeneratedReportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GeneratedReportId");

                    b.HasIndex("UserId");

                    b.ToTable("ReportExports", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ReportGenerationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AiProvider")
                        .HasColumnType("int");

                    b.Property<Guid>("GeneratedReportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PromptText")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RawResponse")
                        .HasMaxLength(20000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ReportRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GeneratedReportId");

                    b.HasIndex("ReportRequestId");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("ReportGenerationRuns", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ReportRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BudgetConsiderations")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("BudgetConsiderations");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentTechnologyStack")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("CurrentTechnologyStack");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("IndustryOrDomain")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("IndustryOrDomain");

                    b.Property<string>("MustAvoid")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("MustAvoid");

                    b.Property<string>("MustInclude")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("MustInclude");

                    b.Property<string>("PerformanceRequirements")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("PerformanceRequirements");

                    b.Property<int>("PreferredAiProvider")
                        .HasColumnType("int");

                    b.Property<int>("ReportLength")
                        .HasColumnType("int");

                    b.Property<int>("ReportMode")
                        .HasColumnType("int");

                    b.Property<string>("SecurityRequirements")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("SecurityRequirements");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Style")
                        .HasColumnType("int");

                    b.Property<string>("TargetAudience")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("TechnicalDepth")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ReportRequests", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ReportStylePreset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DefaultDepth")
                        .HasColumnType("int");

                    b.Property<int>("DefaultStyle")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("RecommendedAudience")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("RecommendedAudience");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.ToTable("ReportStylePresets", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ReportTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("SystemPrompt");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserPromptTemplate")
                        .IsRequired()
                        .HasMaxLength(6000)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UserPromptTemplate");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.ToTable("ReportTemplates", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Data.Identity.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Data.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CriteriaPreset", b =>
                {
                    b.OwnsMany("Domain.ValueObjects.SuggestedCriterion", "SuggestedCriteria", b1 =>
                        {
                            b1.Property<Guid>("CriteriaPresetId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(300);

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(150);

                            b1.HasKey("CriteriaPresetId", "__synthesizedOrdinal");

                            b1.ToTable("CriteriaPresets");

                            b1
                                .ToJson("CriteriaJson")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("CriteriaPresetId");
                        });

                    b.Navigation("SuggestedCriteria");
                });

            modelBuilder.Entity("Domain.Entities.GeneratedReport", b =>
                {
                    b.OwnsMany("Domain.Entities.ReportCitation", "Citations", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("AccessedAtUtc")
                                .HasColumnType("datetime2");

                            b1.Property<Guid>("GeneratedReportId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Notes")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)");

                            b1.Property<DateTime?>("PublishedAtUtc")
                                .HasColumnType("datetime2");

                            b1.Property<int>("SortOrder")
                                .HasColumnType("int");

                            b1.Property<string>("SourceName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Url");

                            b1.HasKey("Id");

                            b1.HasIndex("GeneratedReportId");

                            b1.ToTable("ReportCitations", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("GeneratedReportId");
                        });

                    b.OwnsMany("Domain.Entities.ReportRecommendation", "Recommendations", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("GeneratedReportId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Reasoning")
                                .IsRequired()
                                .HasMaxLength(1500)
                                .HasColumnType("nvarchar(1500)");

                            b1.Property<string>("RecommendedOption")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<string>("Scenario")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)");

                            b1.Property<int>("SortOrder")
                                .HasColumnType("int");

                            b1.Property<int>("Strength")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("GeneratedReportId");

                            b1.ToTable("ReportRecommendations", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("GeneratedReportId");
                        });

                    b.OwnsMany("Domain.ValueObjects.QualityWarning", "QualityWarnings", b1 =>
                        {
                            b1.Property<Guid>("GeneratedReportId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<string>("Code")
                                .IsRequired();

                            b1.Property<string>("Message")
                                .IsRequired()
                                .HasMaxLength(500);

                            b1.Property<int>("Severity");

                            b1.HasKey("GeneratedReportId", "__synthesizedOrdinal");

                            b1.ToTable("GeneratedReports");

                            b1
                                .ToJson("QualityWarningsJson")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("GeneratedReportId");
                        });

                    b.OwnsOne("Domain.ValueObjects.ReportContent", "Content", b1 =>
                        {
                            b1.Property<Guid>("GeneratedReportId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Markdown")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("MarkdownContent");

                            b1.Property<string>("Summary")
                                .IsRequired()
                                .HasMaxLength(600)
                                .HasColumnType("nvarchar(600)")
                                .HasColumnName("Summary");

                            b1.HasKey("GeneratedReportId");

                            b1.ToTable("GeneratedReports");

                            b1.WithOwner()
                                .HasForeignKey("GeneratedReportId");
                        });

                    b.Navigation("Citations");

                    b.Navigation("Content")
                        .IsRequired();

                    b.Navigation("QualityWarnings");

                    b.Navigation("Recommendations");
                });

            modelBuilder.Entity("Domain.Entities.ReportGenerationRun", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.ErrorDetail", "ErrorDetail", b1 =>
                        {
                            b1.Property<Guid>("ReportGenerationRunId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("ErrorCode")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ErrorCode");

                            b1.Property<string>("ErrorMessage")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)")
                                .HasColumnName("ErrorMessage");

                            b1.HasKey("ReportGenerationRunId");

                            b1.ToTable("ReportGenerationRuns");

                            b1.WithOwner()
                                .HasForeignKey("ReportGenerationRunId");
                        });

                    b.OwnsOne("Domain.ValueObjects.GenerationTiming", "Timing", b1 =>
                        {
                            b1.Property<Guid>("ReportGenerationRunId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime?>("CompletedAtUtc")
                                .HasColumnType("datetime2")
                                .HasColumnName("CompletedAtUtc");

                            b1.Property<DateTime>("StartedAtUtc")
                                .HasColumnType("datetime2")
                                .HasColumnName("StartedAtUtc");

                            b1.HasKey("ReportGenerationRunId");

                            b1.ToTable("ReportGenerationRuns");

                            b1.WithOwner()
                                .HasForeignKey("ReportGenerationRunId");
                        });

                    b.OwnsOne("Domain.ValueObjects.TokenUsage", "TokenUsage", b1 =>
                        {
                            b1.Property<Guid>("ReportGenerationRunId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("InputTokens")
                                .HasColumnType("int")
                                .HasColumnName("InputTokens");

                            b1.Property<int>("OutputTokens")
                                .HasColumnType("int")
                                .HasColumnName("OutputTokens");

                            b1.HasKey("ReportGenerationRunId");

                            b1.ToTable("ReportGenerationRuns");

                            b1.WithOwner()
                                .HasForeignKey("ReportGenerationRunId");
                        });

                    b.Navigation("ErrorDetail");

                    b.Navigation("Timing");

                    b.Navigation("TokenUsage");
                });

            modelBuilder.Entity("Domain.Entities.ReportRequest", b =>
                {
                    b.OwnsMany("Domain.Entities.ReportCriterion", "Criteria", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Description")
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)")
                                .HasColumnName("Name");

                            b1.Property<Guid>("ReportRequestId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("SortOrder")
                                .HasColumnType("int");

                            b1.Property<int>("Weight")
                                .HasColumnType("int")
                                .HasColumnName("Weight");

                            b1.HasKey("Id");

                            b1.HasIndex("ReportRequestId");

                            b1.ToTable("ReportCriteria", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ReportRequestId");
                        });

                    b.OwnsMany("Domain.Entities.ReportTopic", "Topics", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Description")
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)")
                                .HasColumnName("Name");

                            b1.Property<Guid>("ReportRequestId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("SortOrder")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("ReportRequestId");

                            b1.ToTable("ReportTopics", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ReportRequestId");
                        });

                    b.Navigation("Criteria");

                    b.Navigation("Topics");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Infrastructure.Data.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Infrastructure.Data.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Infrastructure.Data.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Infrastructure.Data.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Data.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Infrastructure.Data.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
